### ISSUE TITLE
evcc in homebrew cannot find config under $HOMEBREW_PREFIX/etc

### ISSUE THREAD

**Issue by othorg** [evcc-io/homebrew-tap#1]
the homebrew port of evcc looks for configs in  "~/evcc.yaml" or "/etc/evcc.yaml"

The config file should better be found under $HOMEBREW_PREFIX/etc this would be more a "brewable" style

and thanks, it's a cool idea to provide a brew port for this project!

**Comment by andig** [comment]
I think this should only be done if installed via brew. For my install, the prefix is empty. Is this really worth doing?
